### ISSUE TITLE
Rename all function name in frontend/pages

### ISSUE THREAD

**Issue by haianhltr** [cgTeate/CapStone-Project#37]
<img width="185" alt="Screen Shot 2022-10-18 at 10 22 46 PM" src="https://user-images.githubusercontent.com/91930806/196473459-d012a607-385a-4622-bc0d-b4365f79fa15.png">
These page all have _export default function homePage()_
Will replace after create more pages

**Comment by haianhltr** [comment]
After fix this, we can polish the code up

**Comment by cgTeate** [comment]
I finished replacing the current pages with "homePage()" as the function name.
